name: Build LaTeX Resume and Deploy to Portfolio

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tex'
      - '**/*.bib'
      - '**/*.png'
      - '**/*.jpg'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout LaTeX Resume Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX Resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode

      - name: Rename PDF
        run: mv main.pdf resume.pdf

      - name: Upload Compiled Resume PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Compiled Resume
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf

      - name: Checkout Portfolio Repository
        uses: actions/checkout@v4
        with:
          repository: Apex077/Portfolio-V2
          path: portfolio
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Move Resume to Public Directory
        run: mv resume.pdf portfolio/public/resume.pdf

      - name: Commit and Push to Portfolio Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: portfolio
          commit_message: 'Automated: update resume [skip ci]'
          file_pattern: public/resume.pdf
          token: ${{ secrets.DEPLOY_TOKEN }}
